import csv
import json
from collections import Counter
from pathlib import Path

from text.normalize import normalize
from text.tokenize import tokenize
from text.stem import stem


AUTO_CANDIDATES_PATH = Path(
    "data/auto_candidates.tsv"
)

CORPUS_PATH = Path(
    "data/news_dedup/news_dedup.jsonl"
)


# ============================================================
# LOAD CORPUS FREQUENCIES
# ============================================================

def load_corpus_forms():
    """
    Count surface-form frequencies in the real news corpus.
    """

    frequencies = Counter()

    if not CORPUS_PATH.exists():
        return frequencies

    with CORPUS_PATH.open(
        "r",
        encoding="utf-8",
    ) as file:

        for line in file:

            if not line.strip():
                continue

            article = json.loads(line)

            text = (
                article.get("headline", "")
                + " "
                + article.get("body", "")
            )

            for token in tokenize(
                normalize(text)
            ):
                frequencies[token] += 1

    return frequencies


# ============================================================
# LOAD STRONG AUTO CANDIDATES
# ============================================================

def load_auto_candidates():
    """
    Load STRONG candidates generated by
    scripts/analyze_auto_candidates.py.
    """

    if not AUTO_CANDIDATES_PATH.exists():
        return {}

    candidates = {}

    with AUTO_CANDIDATES_PATH.open(
        "r",
        encoding="utf-8",
        newline="",
    ) as file:

        reader = csv.DictReader(
            file,
            delimiter="\t",
        )

        for row in reader:

            if row.get("classification") != "STRONG":
                continue

            stem_word = row.get(
                "stem",
                "",
            ).strip()

            if stem_word:
                candidates[stem_word] = row

    return candidates


# ============================================================
# PARSE SURFACE FORMS
# ============================================================

def parse_surface_forms(surface_forms):
    """
    Convert:

        किया:11438, किये:24

    into:

        {
            "किया": 11438,
            "किये": 24
        }
    """

    forms = {}

    if not surface_forms:
        return forms

    for item in surface_forms.split(","):

        item = item.strip()

        if not item or ":" not in item:
            continue

        form, frequency = item.rsplit(
            ":",
            1,
        )

        form = form.strip()

        try:
            frequency = int(frequency)
        except ValueError:
            continue

        if form:
            forms[form] = frequency

    return forms


# ============================================================
# EDIT DISTANCE
# ============================================================

def edit_distance(a, b):
    """
    Levenshtein edit distance.
    """

    if a == b:
        return 0

    if not a:
        return len(b)

    if not b:
        return len(a)

    previous = list(
        range(len(b) + 1)
    )

    for i, char_a in enumerate(a, 1):

        current = [i]

        for j, char_b in enumerate(b, 1):

            insert_cost = current[j - 1] + 1
            delete_cost = previous[j] + 1
            replace_cost = (
                previous[j - 1]
                + (char_a != char_b)
            )

            current.append(
                min(
                    insert_cost,
                    delete_cost,
                    replace_cost,
                )
            )

        previous = current

    return previous[-1]


# ============================================================
# COMMON PREFIX
# ============================================================

def common_prefix_length(a, b):
    """
    Number of characters shared from the beginning.
    """

    length = 0

    for char_a, char_b in zip(a, b):

        if char_a != char_b:
            break

        length += 1

    return length


# ============================================================
# COMMON HINDI INFLECTIONS
# ============================================================

def is_common_inflection(base, form):
    """
    Detect common Hindi inflectional relationships.

    This is deliberately moderate. It is not intended to
    be a complete Hindi morphological analyzer.
    """

    if base == form:
        return True

    # --------------------------------------------------------
    # Masculine forms
    #
    # लड़का -> लड़के
    # लड़का -> लड़कों
    # --------------------------------------------------------

    if base.endswith("ा"):

        root = base[:-1]

        if form in {
            root + "े",
            root + "ों",
            root + "ें",
        }:
            return True

    # --------------------------------------------------------
    # Feminine forms
    #
    # लड़की -> लड़कियाँ
    # लड़की -> लड़कियों
    # --------------------------------------------------------

    if base.endswith("ी"):

        root = base[:-1]

        if form in {
            root + "ियाँ",
            root + "ियों",
            root + "याँ",
            root + "यों",
        }:
            return True

    # --------------------------------------------------------
    # Plural / oblique endings
    # --------------------------------------------------------

    suffixes = (
        "ों",
        "ें",
        "ओं",
        "एं",
        "याँ",
        "यों",
        "ियों",
        "ियाँ",
        "ाओं",
        "ाएं",
        "ाएँ",
    )

    for suffix in suffixes:

        if not form.endswith(suffix):
            continue

        root = form[:-len(suffix)]

        if root == base:
            return True

        if root + "ा" == base:
            return True

        if root + "ी" == base:
            return True

    # --------------------------------------------------------
    # Common verbal endings
    # --------------------------------------------------------

    verbal_endings = (
        "ना",
        "ने",
        "नी",
        "ता",
        "ती",
        "ते",
        "कर",
        "के",
        "गा",
        "गी",
        "गे",
    )

    if len(base) >= 3:

        for ending in verbal_endings:

            if form == base + ending:
                return True

    return False


# ============================================================
# RELATED FORM CHECK
# ============================================================

def forms_are_related(base, form):
    """
    Decide whether two surface forms are plausible
    variants of the same word.
    """

    if base == form:
        return True

    # Same light-stem class is mandatory.
    if stem(base) != stem(form):
        return False

    # Explicit Hindi inflection.
    if is_common_inflection(base, form):
        return True

    if len(base) < 4 or len(form) < 4:
        return False

    distance = edit_distance(
        base,
        form,
    )

    prefix = common_prefix_length(
        base,
        form,
    )

    # Strong shared prefix.
    if (
        prefix >= 3
        and distance <= 2
    ):
        return True

    # Longer words can tolerate another edit.
    if (
        prefix >= 4
        and distance <= 3
    ):
        return True

    # Small relative edit distance.
    if (
        distance <= 2
        and distance / max(
            len(base),
            len(form),
        ) <= 0.30
    ):
        return True

    return False


# ============================================================
# CANONICAL FORM SELECTION
# ============================================================

def canonical_score(
    form,
    frequency,
):
    """
    Score a surface form for canonical selection.

    We do NOT simply choose the most frequent form.

    Prefer forms that look like a base/lemma:
      - ending in ा
      - ending in ई/ी where appropriate
      - shorter forms
      - high frequency

    This prevents cases such as:

        रुपया:36
        रुपये:3527

    from choosing "रुपये" merely because it is more frequent.
    """

    score = 0.0

    # Frequency matters, but should not dominate morphology.
    score += min(
        frequency,
        5000,
    ) / 5000.0

    # Base-like Hindi noun/adjective ending.
    if form.endswith("ा"):
        score += 3.0

    # Feminine/base-like ending.
    if form.endswith("ी"):
        score += 1.5

    # Forms ending in oblique/plural markers are less likely
    # to be the canonical form.
    oblique_suffixes = (
        "ों",
        "ें",
        "ओं",
        "एं",
        "याँ",
        "यों",
        "ियों",
        "ाओं",
        "ाएं",
        "ाएँ",
    )

    for suffix in oblique_suffixes:

        if form.endswith(suffix):
            score -= 2.0
            break

    # Slight preference for shorter forms.
    score -= len(form) * 0.03

    return score


def find_canonical_form(
    stem_word,
    forms,
):
    """
    Select a linguistically sensible canonical form.

    Frequency is considered, but morphological shape gets
    priority so that plural/oblique forms do not automatically
    become the canonical form.
    """

    candidates = []

    for form, frequency in forms.items():

        if stem(form) != stem_word:
            continue

        score = canonical_score(
            form,
            frequency,
        )

        candidates.append(
            (
                score,
                frequency,
                form,
            )
        )

    if not candidates:
        return None

    candidates.sort(
        key=lambda item: (
            item[0],
            item[1],
        ),
        reverse=True,
    )

    return candidates[0][2]


# ============================================================
# CANDIDATE SAFETY FILTER
# ============================================================

def candidate_is_safe(
    stem_word,
    forms,
    avg_similarity,
    max_collision,
):
    """
    Decide whether a STRONG statistical candidate should
    become an AUTO class.

    We deliberately keep this broad enough that AUTO remains
    useful. The candidate generator already performed the
    statistical discovery.
    """

    if len(forms) < 2:
        return False

    if avg_similarity < 0.67:
        return False

    if max_collision > 0.25:
        return False

    # Every form must at least belong to the same light-stem
    # class. This is our first linguistic safety check.
    for form in forms:

        if stem(form) != stem_word:
            return False

    # There must be at least one plausible relation between
    # two forms.
    ordered = sorted(
        forms.items(),
        key=lambda item: item[1],
        reverse=True,
    )

    related_count = 0

    for i in range(
        len(ordered)
    ):

        form_a = ordered[i][0]

        for j in range(
            i + 1,
            len(ordered),
        ):

            form_b = ordered[j][0]

            if forms_are_related(
                form_a,
                form_b,
            ):
                related_count += 1

    if related_count == 0:
        return False

    return True


# ============================================================
# BUILD AUTO MAP
# ============================================================

def build_auto_map(
    candidates,
    corpus_frequencies,
):
    """
    Build:

        surface form -> canonical form
    """

    auto_map = {}

    approved_classes = 0

    for stem_word, row in candidates.items():

        forms = parse_surface_forms(
            row.get(
                "surface_forms",
                "",
            )
        )

        if len(forms) < 2:
            continue

        # ACTUAL candidate TSV column names.
        try:
            avg_similarity = float(
                row.get(
                    "avg_similarity",
                    0,
                )
            )
        except (
            TypeError,
            ValueError,
        ):
            avg_similarity = 0.0

        try:
            max_collision = float(
                row.get(
                    "max_collision",
                    1,
                )
            )
        except (
            TypeError,
            ValueError,
        ):
            max_collision = 1.0

        if not candidate_is_safe(
            stem_word,
            forms,
            avg_similarity,
            max_collision,
        ):
            continue

        canonical = find_canonical_form(
            stem_word,
            forms,
        )

        if canonical is None:
            continue

        # Canonical must occur in the real corpus.
        if corpus_frequencies:

            if corpus_frequencies.get(
                canonical,
                0,
            ) == 0:
                continue

        class_mappings = {}

        for surface_form in forms:

            if surface_form == canonical:
                continue

            # Same light-stem class.
            if stem(surface_form) != stem_word:
                continue

            # Surface form must be related to the canonical.
            if not forms_are_related(
                canonical,
                surface_form,
            ):
                continue

            class_mappings[
                surface_form
            ] = canonical

        if not class_mappings:
            continue

        # ----------------------------------------------------
        # Conflict protection
        # ----------------------------------------------------

        conflict = False

        for surface_form, target in (
            class_mappings.items()
        ):

            existing = auto_map.get(
                surface_form
            )

            if (
                existing is not None
                and existing != target
            ):
                conflict = True
                break

        if conflict:
            continue

        auto_map.update(
            class_mappings
        )

        approved_classes += 1

    print(
        f"Approved AUTO classes: "
        f"{approved_classes}"
    )

    return auto_map


# ============================================================
# INITIALIZE
# ============================================================

CORPUS_FREQUENCIES = (
    load_corpus_forms()
)

AUTO_CANDIDATES = (
    load_auto_candidates()
)

AUTO_MAP = build_auto_map(
    AUTO_CANDIDATES,
    CORPUS_FREQUENCIES,
)


# ============================================================
# PUBLIC API
# ============================================================

def stem_auto(word: str) -> str:
    """
    Apply selective AUTO stemming.

    Words outside approved classes remain unchanged.
    """

    if not word:
        return word

    return AUTO_MAP.get(
        word,
        word,
    )


def is_auto_stemmed(
    word: str,
) -> bool:
    """
    Return True if AUTO changes the word.
    """

    return (
        stem_auto(word)
        != word
    )


def auto_stem_count():
    """
    Return number of approved mappings.
    """

    return len(AUTO_MAP)


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    print(
        f"Candidate stem classes: "
        f"{len(AUTO_CANDIDATES)}"
    )

    print(
        f"Approved surface-form mappings: "
        f"{len(AUTO_MAP)}"
    )

    print()
    print("EXAMPLES")
    print("-" * 60)

    examples = [

        # Expected mappings
        "किया",
        "किये",

        "दिया",
        "दिये",

        "रुपया",
        "रुपये",
        "रुपयों",

        "लिया",
        "लिये",

        "पार्टी",
        "पार्टियों",
        "पार्टियां",

        "महिला",
        "महिलाओं",
        "महिलाएं",

        "विधानसभा",
        "विधानसभाओं",

        "प्रक्रिया",
        "प्रक्रियाओं",
        "प्रक्रियाएं",

        # Dangerous candidates
        "आगे",
        "आगा",

        "भारी",
        "भारती",

        "सूचना",
        "सूची",

        "पत्नी",
        "पत्ता",
        "पत्ते",
        "पत्ती",
    ]

    for word in examples:

        print(
            f"{word:<15} -> "
            f"{stem_auto(word)}"
        )